
set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/zigcc.sh" -target ${ZIG_TARGET})
set(CMAKE_C_COMPILER_ID "Clang")

set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/zigar.sh")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zigranlib.sh")
set(CMAKE_ASM_COMPILER "${CMAKE_CURRENT_LIST_DIR}/zigcc.sh" -target ${ZIG_TARGET})
set(CMAKE_ASM_COMPILERID "Clang")

set(CMAKE_RC_COMPILER "${CMAKE_CURRENT_LIST_DIR}/zigrc.sh")
set(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> <FLAGS> <DEFINES> -- <SOURCE> <OBJECT>")
set(CMAKE_RC_COMPILER_ID "Clang")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
